### ISSUE TITLE
how did you get the picture of model raw output?

### ISSUE THREAD

**Issue by yjydiancom** [dcaffo98/path-planning-cnn#2]
Sorry to bother you again.I also want to ask, how did you get the picture of model raw output?
https://github.com/dcaffo98/path-planning-cnn/blob/8d226223824c24e8d8baaa6cb08201631a342d65/evaluation.py#L42
Is this line visualized?I still don't know the specific operation.

**Comment by dcaffo98** [comment]
`out` is indeed the model raw output, but it is not displayed anywhere now. You should be able to plot it as
```
import matplotlib.pyplot as plt
...
out = model(map, start, goal).squeeze() 
plt.imshow(out)
plt.show()
```

**Comment by yjydiancom** [comment]
Thank you! I'm just starting to learn about this and I really appreciate you answering my questions so patiently.
