### ISSUE TITLE
Modify input image size

### ISSUE THREAD

**Issue by yjydiancom** [dcaffo98/path-planning-cnn#3]
If I need to modify the input image size to 480*480, do I need to retrain or just modify some parameters?
![image](https://github.com/dcaffo98/path-planning-cnn/assets/91858119/f84bb13b-e93a-40e5-bb24-740df60da37c)
![image](https://github.com/dcaffo98/path-planning-cnn/assets/91858119/e5d6f52c-1f0e-4adf-b837-ad0b55e92169)
This is the parameter I have changed, but it still reports an error. The error is as follows:
![image](https://github.com/dcaffo98/path-planning-cnn/assets/91858119/a11dbf57-77f7-4ef8-8410-512e69074227)

**Comment by dcaffo98** [comment]
Hi, sorry for the late response.
Actually, the positional encoding doesn't store any learnable parameters, so you should be able to load it from the checkpoint using  [`strict=False`](https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=load_state_dict#torch.nn.Module.load_state_dict).

**Comment by yjydiancom** [comment]
Ok, thank you very much for your reply. I changed the size of the input image to 100×100 now. I will try this method afterwards.
