### ISSUE TITLE
Bad Result

### ISSUE THREAD

**Issue by HyWu23** [dcaffo98/path-planning-cnn#5]
I trained the model for 40 peochs.
But Most the result (paths) are not valid, when i loaded the weight, and use the function "b_search".
The only pics that valid looked like this
![F12C6C5E-DD04-406B-B169-5BE7B473FE1D](https://github.com/dcaffo98/path-planning-cnn/assets/163992889/4601e709-a2ca-40ae-9fc9-2931853119d0)

BTW, I didn’t change the model. Any suggestions or tricks while training?🤣

**Comment by yjydiancom** [comment]
需要参照他的论文修改参数

**Comment by HyWu23** [comment]
> 需要参照他的论文修改参数

是哪篇文章，能提供一下嘛。

**Comment by yjydiancom** [comment]
read me里的

**Comment by Siyou-Chen** [comment]
请问是不是只有batch size需要修改呢？还需要修改什么啊
